# Generated by Django 4.0.4 on 2022-05-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConasReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=50)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Software Eng', 'Software Eng'), ('Cyber Security', 'Cyber Security'), ('Microbiology', 'Microbiology'), ('History', 'History'), ('Chemistry', 'Chemistry'), ('BioChemistry', 'BioChemistry'), ('Mathematics', 'Mathematics'), ('Statistics', 'Statistics'), ('Physics', 'Physics')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ConasReg',
                'verbose_name_plural': 'ConasRegs',
                'ordering': ['department', 'level'],
            },
        ),
        migrations.CreateModel(
            name='CourseReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=50)),
                ('department', models.CharField(choices=[('Accounting', 'Accounting'), ('Banking', 'Banking'), ('Business Admin', 'Business Admin'), ('Economics', 'Economics'), ('History', 'History'), ('Inter- Relations', 'Inter- Relations'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Mass Comm', 'Mass Comm'), ('Criminology', 'Criminology')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CourseReg',
                'verbose_name_plural': 'CourseRegs',
                'ordering': ['department', 'level'],
            },
        ),
    ]
